from typing import List
from fastapi import APIRouter, status, Depends, Response
from sqlalchemy.orm import Session

import models
import schemas
import database

router = APIRouter(
    tags = ["Blog"],
    prefix="/blog"
)

def get_db():
    db = database.SessionLocal()
    try :
        yield db
    finally :
        db.close()
        

@router.post(
    '', 
    status_code=status.HTTP_201_CREATED
)
def create(
    request:schemas.Blog, 
    db: Session = Depends(get_db)
):
    new_blog = models.Blog(**request.__dict__)
    db.add(new_blog)
    db.commit()
    db.refresh(new_blog)   # get stuff like id generated by the database
    return new_blog


@router.get(
    '',
    response_model=List[schemas.ShowBlog]
)
def all_blogs(
    db: Session = Depends(get_db)
):
    blogs = db.query(models.Blog).all()
    return blogs


@router.get(
    '/{id}',
    status_code=200,
    response_model=schemas.ShowBlog
)
def get_single_blog(
    id:int, response : Response, 
    db: Session = Depends(get_db)
):
    blog = db.query(models.Blog).filter(models.Blog.id==id).first()
    if not blog :
        response.status_code = status.HTTP_404_NOT_FOUND
        return {
            "message" : f"Blog with id {id} not available"
        }
    return blog


@router.delete(
    '/{id}', 
    status_code=status.HTTP_204_NO_CONTENT,
)
def destroy(
    id:int, 
    response : Response, 
    db: Session = Depends(get_db)
):
    blog = db.query(models.Blog).filter(models.Blog.id==id).first()
    if not blog :
        response.status_code = status.HTTP_404_NOT_FOUND
        return {
            "message" : f"Blog with id {id} not available"
        }
    db.query(models.Blog).filter(models.Blog.id==id).delete()
    db.commit()


@router.put(
    '/{id}', 
    status_code=status.HTTP_202_ACCEPTED,
)
def edit(
    id:int, 
    request : schemas.Blog, 
    response : Response, 
    db: Session = Depends(get_db)
):
    blogs = db.query(models.Blog).filter(models.Blog.id==id)
    if(len(blogs.all())==0):
        response.status_code = status.HTTP_404_NOT_FOUND
        return {
            "message" : f"Blog with id {id} not available"
        }
    blogs.update(
        {
            "title" : request.title, 
            "body" : request.body
        }, 
        synchronize_session=False
    )
    db.commit()
    return {
        "message" : "Blog Updated"
    }
